#
# Copyright 2016-2018 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - restore_cache:
          key: maven-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Download dependencies
          command: mvn --fail-never dependency:go-offline || true

      - save_cache:
          key: maven-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - setup_remote_docker

      - run:
          name: Run acceptance tests
          command: ./scripts/runAcceptanceTests.sh

      - run:
          name: Collect logs
          command: |
            mkdir /tmp/artifacts
            cp target/*.log /tmp/artifacts/

      - store_artifacts:
          path: /tmp/artifacts
